#!/bin/sh
device=$(gawk '$2=="hppev" {print $2}' /proc/devices)
if [  $device = "hppev" ]; then 
../bin/hppev disconnect pev.cfg
/sbin/rmmod pev
echo "it is safe now to disconnect the PEV1100"
exit 1
fi
echo "hotplug driver must be installed to disconnect PEV1100"

