#!/bin/sh

XENO_X86="pev-xeno-x86"
LINUX_X86="pev-linux-x86"
LINUX_X86_32="pev-linux-x86_32"
LINUX_X86_64="pev-linux-x86_64"
LINUX_PPC="pev-linux-ppc"
HP="hppev"

if [ $1 = $XENO_X86 ]; then
device="pev"
mode="666"
group="wheel"

echo loading PEV1100 xenomai driver $XENO_X86.ko
/sbin/insmod $XENO_X86.ko
if [  $? -ne 0 ]; then 
exit 1
fi

elif [ $1 = $LINUX_X86_64 ]; then
device="pev"
mode="666"
group="wheel"

echo loading PEV1100 linux driver $LINUX_X86_64.ko
/sbin/insmod $LINUX_X86_64.ko
if [  $? -ne 0 ]; then 
exit 1
fi

elif [ $1 = $LINUX_X86_32 ]; then
device="pev"
mode="666"
group="wheel"

echo loading PEV1100 linux driver $LINUX_X86_32.ko
/sbin/insmod $LINUX_X86_32.ko
if [  $? -ne 0 ]; then 
exit 1
fi

elif [ $1 = $LINUX_PPC ]; then
device="pev"
mode="666"
group="root"

echo loading PEV1100 linux driver $LINUX_PPC.ko
/sbin/insmod $LINUX_PPC.ko
if [  $? -ne 0 ]; then 
exit 1
fi

elif [ $1 = $HP ]; then
device="hppev"
mode="666"
group="wheel"

echo loading PEV1100 xenomai driver $HP.ko
/sbin/insmod $HP.ko
if [  $? -ne 0 ]; then 
exit 1
fi

else
echo cannot load module $1
exit 1
fi

if [ $device = "pev" ]; then

echo creating PEV devices
major=$(gawk '$2=="pev" {print $1}' /proc/devices)

rm -f /dev/${device}*
mknod /dev/$device c $major 0
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
mknod /dev/${device}4 c $major 4
mknod /dev/${device}5 c $major 5
mknod /dev/${device}6 c $major 6
mknod /dev/${device}7 c $major 7
mknod /dev/${device}8 c $major 8
mknod /dev/${device}9 c $major 9
mknod /dev/${device}10 c $major 10
mknod /dev/${device}11 c $major 11
mknod /dev/${device}12 c $major 12
mknod /dev/${device}13 c $major 13
mknod /dev/${device}14 c $major 14
mknod /dev/${device}15 c $major 15

chgrp $group /dev/$device
chgrp $group /dev/${device}*
chmod $mode /dev/$device
chmod $mode /dev/${device}*

elif [ $device = "hppev" ]; then

echo creating HPPEV device
major=$(gawk '$2=="hppev" {print $1}' /proc/devices)

rm -f /dev/$device
mknod /dev/$device c $major 0

chgrp $group /dev/$device
chmod $mode /dev/$device

fi
